// <auto-generated />
using System;
using ConcurrentOrdering.Web.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConcurrentOrdering.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190606021408_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConcurrentOrdering.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AvailableUnits");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableUnits = 3,
                            ImageUrl = "https://i.ytimg.com/vi/zRmh1aFHHQQ/hqdefault.jpg",
                            Name = "Thimbleweed Park Diskette"
                        },
                        new
                        {
                            Id = 2,
                            AvailableUnits = 3,
                            ImageUrl = "https://i.ytimg.com/vi/GWMtT0EFX_0/hqdefault.jpg",
                            Name = "Return of the Obra Dinn"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
